### ISSUE TITLE
Coding Standards

### ISSUE THREAD

**Issue by nathansmonk** [sitemorse/sci-wordpress#4]
I ran this through WordPress coding standards and began to start fixing the errors, but there are quite a lot.

I ran `phpcbf` which was able to fix a large proportion of them, but one file wasn't able to be fixed for whatever reason.

I've got everything in a branch here: https://github.com/wearesmile/sci-wordpress/tree/coding-standards

Would be good to bring this in line with standards and hopefully got this most of the way there. Should I merge these changes back to this repo?

**Comment by ChristopherDBerry** [comment]
I haven't looked at this in detail but in principle sounds OK to merge back.

**Comment by jribbens** [comment]
Presumably fixed by PR #5 6a4d7e70fd47d4cc00e79df878824b117b0aa841

**Comment by nathansmonk** [comment]
I don't think it was @jribbens

**Comment by nathansmonk** [comment]
On review it wasn't. I have a new PR that I will lodge now.
